In [ ]:
import pandas as pd

df = pd.read_feather('../data/rad/rad.feather')
df.head()

df_hat = df[['x_hat', 'y_hat', 'z_hat']]

df_rad_extra = pd.read_feather('../data/rad/rad_current_speed_temp.feather')
df_rad_extra.head()

df_merged = pd.concat([df_rad_extra.reset_index(drop=True),
                       df_hat.reset_index(drop=True)],
                      axis=1)

df_merged.head()
# df_merged.to_feather('../data/rad/rad_current_speed_temp.feather')

In [13]:
df = pd.read_feather('../data/rad/rad.feather')
df.head()

,time,x,y,z,q0,q1,q2,q3,q4,q5,x_hat,y_hat,z_hat
0,0.000000,-0.186053,-0.013900,0.25,1.645375,-1.279052,-2.650487,-0.979104,0.0,0.0,-0.204480,-0.015277,0.250000
1,0.846160,-0.181287,-0.004773,0.25,1.597134,-1.277415,-2.649175,-0.977958,0.0,0.0,-0.204979,-0.005397,0.250000
2,1.290711,-0.174021,0.002766,0.25,1.554889,-1.277414,-2.649122,-0.977919,0.0,0.0,-0.205024,0.003258,0.250001
3,1.717405,-0.165193,0.008004,0.25,1.522375,-1.276783,-2.648628,-0.977476,0.0,0.0,-0.204810,0.009924,0.250000
4,2.163429,-0.156365,0.013004,0.25,1.487846,-1.276190,-2.648195,-0.977099,0.0,0.0,-0.204345,0.016994,0.250000

In [ ]:
from ikpy.chain import Chain
from ikpy.link import URDFLink, OriginLink
import numpy as np

df = pd.read_feather('../data/aursad/aursad.feather')
df.head()

# --- Define the UR3 robot arm chain ---
UR3_arm = Chain(name="UR3_arm", links=[
    # OriginLink(),  # Base

    # Shoulder Pan
    URDFLink(
        name="shoulder_pan",
        origin_translation=[0, 0, 0.15185],
        origin_orientation=[0, 0, 0],
        rotation=[0, 0, 1],
        # bounds=(-1.65, 1.0)
        # bounds=(-bounds, bounds)
    ),

    # Shoulder Lift
    URDFLink(
        name="shoulder_lift",
        origin_translation=[0, 0.1197, 0],
        origin_orientation=[0, 0, 0],
        rotation=[0, 1, 0],
        # bounds=(-6, -0.0),
        # bounds=(-bounds, bounds)
    ),

    # Elbow
    URDFLink(
        name="elbow",
        origin_translation=[0.24365, 0, 0],
        origin_orientation=[0, 0, 0],
        rotation=[0, 1, 0],
        # bounds=(-2.5, 2.5),
        # bounds=(-bounds, bounds)
    ),

    # Wrist 1
    URDFLink(
        name="wrist_1",
        origin_translation=[0.21325, 0, 0],
        origin_orientation=[0, 0, 0],
        rotation=[0, 1, 0],
        # bounds=(-0.8, 4.0),
        # bounds=(-bounds, bounds)
    ),

    # Wrist 2
    URDFLink(
        name="wrist_2",
        origin_translation=[0, 0.08535, 0],
        origin_orientation=[0, 0, 0],
        rotation=[0, 0, 1],
        # bounds=(-2.5, 3.0),
        # bounds=(-bounds, bounds)
    ),

    # Wrist 3 / End Effector
    URDFLink(
        name="wrist_3",
        origin_translation=[0, 0, 0.0819],
        origin_orientation=[0, 0, 0],
        rotation=[0, 1, 0],
        # bounds=(-1.7, -1.5)
        # bounds=(-bounds, bounds)

    )
])

df_angles = df[['q0', 'q1', 'q2', 'q3', 'q4', 'q5']]
animation_sequence = df_angles.values.tolist()

# print(animation_sequence)

pos_lst = []
for frame in animation_sequence:
    pos = UR3_arm.forward_kinematics(frame)
    
    pos_lst.append(pos[:3,3])

print(pos_lst)
df = pd.concat([df.reset_index(drop=True), pd.DataFrame(pos_lst, columns=['x', 'y', 'z']).reset_index(drop=True)], axis=1)
# df.to_feather('../data/aursad/aursad.feather')
df.head()

[array([0.30631393, 0.23246141, 0.40309835]), array([0.30633357, 0.23244941, 0.40308668]), array([ 0.24250264, -0.2660498 ,  0.35951398]), array([ 0.18825681, -0.30251815,  0.35434567]), array([ 0.18822718, -0.3025449 ,  0.3543422 ]), array([ 0.18826678, -0.30252646,  0.35434682]), array([ 0.18824617, -0.30251931,  0.35432969]), array([ 0.24396378, -0.26484705,  0.35965465]), array([0.30632401, 0.23244173, 0.40308203]), array([0.20753937, 0.3779326 , 0.36732527]), array([0.16622113, 0.40938292, 0.35521187]), array([0.16622628, 0.409344  , 0.35528408]), array([0.16627539, 0.40936137, 0.3552236 ]), array([0.16625642, 0.40943139, 0.3550644 ]), array([0.22341778, 0.36307539, 0.37222501]), array([0.30430888, 0.23138207, 0.40153879]), array([0.18918625, 0.1998794 , 0.33510574]), array([0.1891747 , 0.19987972, 0.33510714]), array([0.18918596, 0.19987713, 0.33509031]), array([0.19059737, 0.20005719, 0.33581815]), array([0.30631119, 0.23245338, 0.40310487]), array([0.17302437, 0.37146325, 0.35606398]), array([0.17025993, 0.37308452, 0.35529716]), array([0.17029363, 0.37307193, 0.35530023]), array([0.17025454, 0.37311229, 0.35525467]), array([0.17024609, 0.37309546, 0.3552887 ]), array([0.17024897, 0.37308212, 0.35530557]), array([0.30630294, 0.23249159, 0.40307523]), array([ 0.35101011, -0.08540334,  0.37142779]), array([ 0.2566593 , -0.23157341,  0.35423115]), array([ 0.25666498, -0.23158393,  0.35420554]), array([ 0.25666787, -0.23156494,  0.3542234 ]), array([ 0.25666094, -0.23158143,  0.35420557]), array([ 0.2566693 , -0.23157195,  0.35422567]), array([0.36894722, 0.01428484, 0.38110001]), array([0.30632225, 0.23246602, 0.40308789]), array([0.17463013, 0.33669892, 0.35530301]), array([0.17463207, 0.33669091, 0.35530965]), array([0.17462551, 0.33669171, 0.35530442]), array([0.1746158 , 0.3366949 , 0.35531886]), array([0.17463427, 0.3366834 , 0.35532987]), array([0.30633488, 0.2324514 , 0.40307631]), array([ 0.32632741, -0.09203055,  0.36852472]), array([ 0.25623882, -0.18895933,  0.35425521]), array([ 0.2562296 , -0.18895874,  0.35426948]), array([ 0.25624931, -0.18895329,  0.35425076]), array([ 0.25624198, -0.18894762,  0.35426168]), array([ 0.25623444, -0.18894111,  0.35427119]), array([0.35738571, 0.05084026, 0.38445948]), array([0.30623259, 0.23256316, 0.40304061]), array([0.1793989 , 0.29992504, 0.35525873]), array([0.17931565, 0.29988204, 0.35551298]), array([0.17942555, 0.29994761, 0.35520694]), array([0.17937916, 0.29993508, 0.35527384]), array([0.17940412, 0.29993461, 0.35524423]), array([0.30632714, 0.23245477, 0.40309439]), array([ 0.30779959, -0.10841481,  0.35961402]), array([ 0.28608676, -0.13967929,  0.35426764]), array([ 0.28608807, -0.1396966 ,  0.35426515]), array([ 0.28608749, -0.13968095,  0.35426126]), array([ 0.28609952, -0.13969379,  0.35424945]), array([ 0.28608874, -0.1396766 ,  0.35427193]), array([0.33238561, 0.17647489, 0.39631895]), array([0.27121774, 0.24509361, 0.39211687]), array([0.15382857, 0.26099682, 0.35611563]), array([0.15382844, 0.26099967, 0.3561865 ]), array([0.15381382, 0.26099512, 0.3561346 ]), array([0.15383932, 0.26099719, 0.35610481]), array([0.1538309 , 0.26099753, 0.35611297]), array([0.30630368, 0.23247219, 0.40309844]), array([ 0.33872535, -0.02040893,  0.36541138]), array([ 0.31326275, -0.0835148 ,  0.35423798]), array([ 0.31326539, -0.08351313,  0.3542307 ]), array([ 0.31326071, -0.08352752,  0.35423044]), array([ 0.31326135, -0.08351286,  0.35423591]), array([ 0.31326195, -0.08353414,  0.35423484]), array([0.31924679, 0.20694476, 0.39925666]), array([0.27236737, 0.23465913, 0.39840355]), array([0.12062345, 0.22925759, 0.35627767]), array([0.12067092, 0.22925432, 0.3562587 ]), array([0.12062927, 0.2292586 , 0.35627374]), array([0.1206262 , 0.2292619 , 0.35626792]), array([0.12124567, 0.22931141, 0.35649088]), array([0.3063009 , 0.23246401, 0.40310911]), array([0.34820667, 0.04367449, 0.36728179]), array([ 0.33530225, -0.02268528,  0.35419603]), array([ 0.33530264, -0.02268562,  0.35420585]), array([ 0.3353138 , -0.02269141,  0.35418509]), array([ 0.33531108, -0.02268901,  0.3541949 ]), array([ 0.3353022 , -0.02269388,  0.35419392]), array([0.34341487, 0.13107753, 0.38368785]), array([0.3022219 , 0.23107456, 0.40379772]), array([0.10811676, 0.20000606, 0.35640681]), array([0.108113  , 0.20000986, 0.35638459]), array([0.10811383, 0.20000747, 0.35640618]), array([0.10810749, 0.20000539, 0.35640954]), array([0.10812844, 0.20000558, 0.35637548]), array([0.12505355, 0.20049087, 0.36634803]), array([0.30632302, 0.23245441, 0.40309686]), array([0.35270094, 0.05849989, 0.35853711]), array([0.35181841, 0.04125669, 0.35423866]), array([0.35180556, 0.04127565, 0.35425044]), array([0.35182101, 0.04126328, 0.35423305]), array([0.35181422, 0.04126699, 0.35424681]), array([0.35180221, 0.04143037, 0.35428247]), array([0.30634808, 0.23242125, 0.40308294]), array([0.22368055, 0.157382  , 0.39189681]), array([0.17115991, 0.14889585, 0.35640981]), array([0.17115237, 0.14890047, 0.35639481]), array([0.17115423, 0.14890087, 0.35641654]), array([0.17115935, 0.14889862, 0.35638478]), array([0.18433379, 0.14894351, 0.36770174]), array([0.30632961, 0.23245888, 0.4030828 ]), array([0.39177552, 0.12067177, 0.36007113]), array([0.39947587, 0.10408504, 0.35413497]), array([0.39947503, 0.10408085, 0.35415974]), array([0.39947026, 0.10408657, 0.35415745]), array([0.3994809 , 0.10407908, 0.35413494]), array([0.39947948, 0.10407061, 0.3541373 ]), array([0.32588079, 0.21382336, 0.39536492]), array([0.31525791, 0.2165406 , 0.45482042]), array([-0.04600928,  0.28314973,  0.52767879]), array([0.00911249, 0.28593414, 0.35406883]), array([0.00910767, 0.28595285, 0.35410291]), array([0.00910874, 0.28594488, 0.35406264]), array([0.00912949, 0.28591994, 0.35407346]), array([0.00912513, 0.28593474, 0.35407522]), array([-0.0324353 ,  0.2979589 ,  0.43748779]), array([0.30719551, 0.19336414, 0.52908882]), array([0.30733616, 0.23190886, 0.40288563]), array([0.43683443, 0.10516254, 0.35408526]), array([0.43683217, 0.10514857, 0.3540977 ]), array([0.4368383 , 0.10512237, 0.35410924]), array([0.43681862, 0.10515186, 0.35410701]), array([0.43684788, 0.10513496, 0.35406594]), array([0.43683501, 0.10514808, 0.35409767]), array([0.30634649, 0.23242921, 0.4030805 ]), array([0.27026786, 0.18376712, 0.59273152]), array([-0.0598836 ,  0.29867131,  0.39476284]), array([-0.03753434,  0.29271605,  0.35410922]), array([-0.03752312,  0.29270383,  0.35411235]), array([-0.03755203,  0.29272697,  0.35412561]), array([-0.03754349,  0.29272013,  0.35411562]), array([-0.03753315,  0.29271509,  0.35411556]), array([-0.08100053,  0.27915234,  0.53678278]), array([0.31298311, 0.22001976, 0.45032123]), array([0.34657127, 0.20128183, 0.39334678]), array([0.43706166, 0.07791217, 0.35440669]), array([0.43706222, 0.07792183, 0.35442344]), array([0.43707013, 0.0779593 , 0.35439496]), array([0.43707421, 0.07793795, 0.35440464]), array([0.43706727, 0.07791514, 0.35439982]), array([0.33167571, 0.21384086, 0.39737835]), array([0.31119143, 0.22197677, 0.451187  ]), array([-0.1135997 ,  0.27114846,  0.53718596]), array([-0.08284747,  0.28885644,  0.35592237]), array([-0.08283443,  0.28884568,  0.35595498]), array([-0.08282965,  0.28885808,  0.35592833]), array([-0.08282161,  0.28885631,  0.3559323 ]), array([-0.0859302 ,  0.28955822,  0.36117455]), array([0.15117098, 0.18443139, 0.6746153 ]), array([0.30632589, 0.23247039, 0.40307735]), array([0.43057579, 0.06346497, 0.3541117 ]), array([0.43057537, 0.06338227, 0.35414023]), array([0.43054548, 0.06344161, 0.35417835]), array([0.4305841 , 0.06343749, 0.35412635]), array([0.43059513, 0.06337947, 0.35408945]), array([0.40471255, 0.11923259, 0.37017601]), array([0.30713589, 0.23140727, 0.40905125]), array([-0.07032032,  0.22958375,  0.64742051]), array([-0.1322828 ,  0.29305241,  0.35414877]), array([-0.13228011,  0.29305096,  0.35415389]), array([-0.13230513,  0.29305335,  0.35414038]), array([-0.13227943,  0.29304405,  0.35414941]), array([-0.13227832,  0.2930468 ,  0.35414825]), array([-0.0868937 ,  0.23577861,  0.63428344]), array([0.30756101, 0.23070195, 0.41249387]), array([0.3002449 , 0.24689368, 0.3978492 ]), array([0.23416256, 0.34356973, 0.35645309]), array([0.22992143, 0.34785589, 0.35427256]), array([0.22990921, 0.34786462, 0.35426662]), array([0.22994285, 0.34784759, 0.35426571]), array([0.22991413, 0.34785216, 0.3542866 ]), array([0.22992091, 0.34786535, 0.3542639 ]), array([0.28265595, 0.28060174, 0.38480948]), array([0.30632129, 0.23245426, 0.40309306]), array([0.24890874, 0.09230033, 0.65770096]), array([0.1971175 , 0.10998568, 0.35729117]), array([0.19809484, 0.10664216, 0.35379739]), array([0.19809185, 0.1066526 , 0.35378322]), array([0.19809324, 0.10664865, 0.35378406]), array([0.19809154, 0.10665706, 0.3537852 ]), array([0.19809447, 0.10664748, 0.35379629]), array([0.19016691, 0.10755383, 0.66553161]), array([0.30636963, 0.23242717, 0.4030404 ]), array([0.30365252, 0.26219079, 0.39277925]), array([0.27264196, 0.34893814, 0.35433077]), array([0.27258374, 0.34903462, 0.35428099]), array([0.27255771, 0.34903308, 0.35431153]), array([0.27257962, 0.34903789, 0.35428282]), array([0.272604  , 0.34903355, 0.35425468]), array([0.27257795, 0.34903199, 0.35429521]), array([0.298511  , 0.28648114, 0.38341781]), array([0.30632297, 0.23246219, 0.40309173]), array([0.16334553, 0.21535382, 0.65214134]), array([-0.22821317,  0.20360852,  0.36776482]), array([-0.22278679,  0.20395805,  0.35418929]), array([-0.22277111,  0.20396077,  0.3541909 ]), array([-0.22278108,  0.20396337,  0.3541849 ]), array([-0.22279381,  0.20395802,  0.35418013]), array([-0.22277837,  0.20396074,  0.35419833]), array([-0.22279565,  0.20395801,  0.35417923]), array([-0.2227954 ,  0.20397916,  0.35414504]), array([-0.23684295,  0.20275205,  0.40038489]), array([0.24665511, 0.22277678, 0.58325155]), array([0.30631371, 0.23248101, 0.40307755]), array([0.32377542, 0.30245489, 0.37978971]), array([0.31448507, 0.35077953, 0.3541654 ]), array([0.31443123, 0.35066956, 0.35444165]), array([0.31448521, 0.35076297, 0.35419594]), array([0.3144812 , 0.35078319, 0.35417796]), array([0.31473822, 0.35088325, 0.35365647]), array([0.31790666, 0.34070586, 0.36016618]), array([0.30952796, 0.23875857, 0.40177013]), array([0.30476471, 0.23209649, 0.43596679]), array([-0.2287648 ,  0.18918339,  0.56646805]), array([-0.26209346,  0.18814087,  0.35238568]), array([-0.26215158,  0.18812809,  0.35244311]), array([-0.2620757 ,  0.1881511 ,  0.35237925]), array([-0.26209603,  0.1881288 ,  0.35239852]), array([-0.26208863,  0.18814119,  0.35239664]), array([-0.09638347,  0.19838713,  0.66888302]), array([0.3063347 , 0.23244375, 0.40459469]), array([0.31932476, 0.24853713, 0.39478021]), array([0.34119163, 0.3049006 , 0.3542642 ]), array([0.34116507, 0.30495908, 0.3542175 ]), array([0.34117244, 0.30495098, 0.35420984]), array([0.3411659 , 0.30494435, 0.35423215]), array([0.34115989, 0.30496293, 0.35422202]), array([0.34115656, 0.30495193, 0.35423927]), array([0.32219292, 0.25294875, 0.39238694]), array([0.30630897, 0.23246892, 0.40310219]), array([-0.03290748,  0.20325332,  0.68868468]), array([-0.298854  ,  0.18966811,  0.35412958]), array([-0.29885586,  0.18967476,  0.35412807]), array([-0.29886254,  0.18967111,  0.3541271 ]), array([-0.29887077,  0.1896602 ,  0.3541203 ]), array([-0.29885789,  0.18967135,  0.3541203 ]), array([-0.2128265 ,  0.19204493,  0.60930427]), array([0.3054636 , 0.23216173, 0.4202487 ]), array([0.27485567, 0.26501539, 0.37894923]), array([0.19988748, 0.31274946, 0.33506443]), array([0.1999249 , 0.3127336 , 0.33505828]), array([0.19987994, 0.31274194, 0.3350911 ]), array([0.27057441, 0.26866079, 0.37610469]), array([0.30450866, 0.23107676, 0.42491068]), array([-0.25290333,  0.21311496,  0.58215125]), array([-0.32951663,  0.22944063,  0.3541087 ]), array([-0.32952941,  0.22946631,  0.35412911]), array([-0.3295156 ,  0.22942801,  0.35411757]), array([-0.32951691,  0.22943635,  0.35411757]), array([-0.05212739,  0.20482571,  0.68746213]), array([0.30632743, 0.2324509 , 0.403078  ]), array([0.34993432, 0.24144505, 0.39461234]), array([0.40408807, 0.25887482, 0.35423599]), array([0.40401687, 0.25885521, 0.35431182]), array([0.40411198, 0.25886226, 0.35421298]), array([0.40413718, 0.25884444, 0.35418712]), array([0.404123  , 0.25886368, 0.35418712]), array([0.40280333, 0.25821596, 0.35635167]), array([0.31636853, 0.23434011, 0.40208592]), array([0.30291801, 0.22878519, 0.43771969]), array([-0.26987144,  0.24154152,  0.54892498]), array([-0.32084411,  0.2689242 ,  0.35416729]), array([-0.32085252,  0.2689125 ,  0.35416425]), array([-0.32081283,  0.26892736,  0.35418366]), array([-0.32084184,  0.26891917,  0.35415554]), array([-0.32153222,  0.267892  ,  0.36488024]), array([0.15225091, 0.20507062, 0.64877274]), array([0.30632276, 0.23245828, 0.40309561]), array([0.37517916, 0.22616533, 0.37933435]), array([0.41082734, 0.21937904, 0.35425741]), array([0.41084888, 0.21935485, 0.3542452 ]), array([0.41084034, 0.21936952, 0.3542496 ]), array([0.41083179, 0.21936902, 0.35424755]), array([0.41082337, 0.21935895, 0.35427766]), array([0.39115389, 0.22352008, 0.3696951 ]), array([0.3063523 , 0.23244528, 0.40306956]), array([0.2569417 , 0.21543879, 0.58671419]), array([-0.16163219,  0.22585693,  0.39617819]), array([-0.14231657,  0.22568176,  0.35381054]), array([-0.14231781,  0.22568192,  0.35382741]), array([-0.14233143,  0.22567338,  0.35380019]), array([-0.14228958,  0.2256864 ,  0.35376764]), array([-0.17139842,  0.22409635,  0.4515803 ]), array([0.29697669, 0.22332077, 0.51160394]), array([0.30643751, 0.23244396, 0.40306916]), array([0.40367516, 0.18874758, 0.36369786]), array([0.41766282, 0.17895069, 0.35440055]), array([0.41764269, 0.17894713, 0.35444527]), array([0.4176124 , 0.17899303, 0.3544676 ]), array([0.41765313, 0.17898056, 0.35439216]), array([0.41765971, 0.17895554, 0.35440821]), array([0.30632212, 0.23246212, 0.40309678]), array([0.33392583, 0.23790474, 0.39916271]), array([0.40405338, 0.25884427, 0.35430359]), array([0.40409921, 0.25887104, 0.35421045]), array([0.40408031, 0.25890553, 0.35421044]), array([0.404063  , 0.25889787, 0.35426734]), array([0.40410591, 0.25888755, 0.35419726]), array([0.40381144, 0.25880682, 0.35462569]), array([0.32685085, 0.23642965, 0.40055208]), array([0.30471831, 0.23023952, 0.42452228]), array([-0.23800636,  0.23411823,  0.58882746]), array([-0.32061631,  0.26963957,  0.35408484]), array([-0.32063637,  0.26965668,  0.35414955]), array([-0.32062557,  0.26961916,  0.35407613]), array([-0.32061558,  0.26964404,  0.35410662]), array([-0.3207785 ,  0.26949995,  0.35547251]), array([0.07711184, 0.20335316, 0.67897253]), array([0.30632781, 0.23246262, 0.40308276]), array([0.16940363, 0.27491179, 0.33708356]), array([0.16442947, 0.27520682, 0.33521185]), array([0.16444233, 0.27520511, 0.33520008]), array([0.16486957, 0.27516792, 0.33539102]), array([0.30631605, 0.2324577 , 0.40310466]), array([0.20211623, 0.20953642, 0.63821873]), array([-0.15191622,  0.22595589,  0.37175168]), array([-0.142314  ,  0.22567928,  0.35381683]), array([-0.14231173,  0.22567488,  0.35381673]), array([-0.1423172 ,  0.22567774,  0.35381069]), array([-0.07350219,  0.20881262,  0.6407379 ]), array([0.30711321, 0.232086  , 0.40885796]), array([0.33479512, 0.22304522, 0.39525796]), array([0.4176356 , 0.17901054, 0.35441324]), array([0.41766505, 0.17896024, 0.35438887]), array([0.41765198, 0.17896107, 0.3543937 ]), array([0.41763839, 0.1789815 , 0.35442109]), array([0.41765314, 0.17897088, 0.35440821]), array([0.41636852, 0.17988331, 0.35536556]), array([0.31780031, 0.22891501, 0.40021213]), array([0.30932517, 0.22618028, 0.44603914]), array([-0.14485402,  0.24609839,  0.54509466]), array([-0.12855233,  0.26227923,  0.35386523]), array([-0.12855026,  0.2622865 ,  0.35400159]), array([-0.12855041,  0.26228655,  0.35384877]), array([-0.12856378,  0.26227799,  0.35385441]), array([-0.1304396 ,  0.2625235 ,  0.35714155]), array([0.11830818, 0.19588623, 0.67968796]), array([0.30632088, 0.23246606, 0.40308147]), array([0.37980481, 0.18425591, 0.37878635]), array([0.42502751, 0.13769364, 0.35430854]), array([0.42505997, 0.13766891, 0.35425137]), array([0.42502054, 0.13768999, 0.35433816]), array([0.42501788, 0.13768564, 0.35434289]), array([0.42524737, 0.13764777, 0.35381376]), array([0.40802199, 0.15733209, 0.36477499]), array([0.30637465, 0.23240798, 0.40307982]), array([0.25554512, 0.19443985, 0.59555416]), array([-0.13838261,  0.2981596 ,  0.39439067]), array([-0.12115544,  0.29753462,  0.35418803]), array([-0.12115792,  0.29753929,  0.35417472]), array([-0.12116773,  0.2975412 ,  0.35417205]), array([-0.12114102,  0.29753692,  0.35416506]), array([-0.14747375,  0.29549279,  0.43026859]), array([0.28874326, 0.20442861, 0.54101955]), array([0.3070851 , 0.2320069 , 0.40290354]), array([0.42460687, 0.11111459, 0.35970931]), array([0.43278081, 0.09666873, 0.35438238]), array([0.43280035, 0.09663906, 0.35436063]), array([0.43275766, 0.09668481, 0.35441587]), array([0.4327549 , 0.09667061, 0.35442615]), array([0.43277353, 0.09667572, 0.35438936]), array([0.32745783, 0.21808737, 0.39798651]), array([0.30918211, 0.22546986, 0.43180125]), array([-0.12015531,  0.2815729 ,  0.57920993]), array([-0.11316598,  0.33272204,  0.3542186 ]), array([-0.1131893 ,  0.33271762,  0.35420504]), array([-0.11316904,  0.33272004,  0.35422225]), array([-0.11318896,  0.33271319,  0.35422415]), array([-0.11331478,  0.33272121,  0.35450915]), array([0.0754918 , 0.19280668, 0.68977164]), array([0.30631497, 0.23244624, 0.40311167]), array([0.38774404, 0.15115306, 0.3809426 ]), array([0.43882467, 0.05418204, 0.35433944]), array([0.43881619, 0.05417525, 0.35438395]), array([0.43881942, 0.05415408, 0.35435831]), array([0.43880506, 0.05418462, 0.35438342]), array([0.43881881, 0.05417945, 0.35435395]), array([0.37263501, 0.17040238, 0.38630698]), array([0.30630029, 0.2324719 , 0.40310474]), array([0.03457061, 0.204576  , 0.68908711]), array([-0.10714589,  0.36769532,  0.35422019]), array([-0.1070625 ,  0.36767857,  0.35426911]), array([-0.10711116,  0.36769555,  0.3542045 ]), array([-0.10711346,  0.36770293,  0.35418761]), array([-0.10710479,  0.36769528,  0.35420836]), array([0.02014595, 0.21011227, 0.68681175]), array([0.30634648, 0.23240149, 0.40310506]), array([0.26381415, 0.180912  , 0.57747821]), array([-0.11156962,  0.40032505,  0.37883422]), array([-0.10272745,  0.40338208,  0.35419366]), array([-0.1026962 ,  0.40334975,  0.35431314]), array([-0.10278342,  0.40338405,  0.35414988]), array([-0.10267918,  0.40338815,  0.35421448]), array([-0.10275015,  0.40337431,  0.35419616]), array([-0.10544041,  0.40401622,  0.34981731]), array([-0.10544525,  0.40402746,  0.34976976]), array([-0.10542678,  0.4040398 ,  0.34976593]), array([-0.10469934,  0.40385754,  0.35080075]), array([-0.12736802,  0.38961089,  0.42815123]), array([0.4445937 , 0.01166477, 0.35434287]), array([0.40311067, 0.12026354, 0.37884047]), array([0.30632655, 0.23245083, 0.40309695]), array([0.4363762 , 0.04293942, 0.36156786]), array([0.44458277, 0.01169102, 0.35436609]), array([0.44459678, 0.01167395, 0.35434787]), array([0.44458809, 0.01166709, 0.3543641 ]), array([0.44456212, 0.01166424, 0.35441671]), array([0.4445762 , 0.01168375, 0.35438849]), array([0.33362501, 0.20911337, 0.39804566]), array([0.30842195, 0.22398786, 0.42988361]), array([-0.11204653,  0.32016319,  0.57929059]), array([-0.10041327,  0.40241023,  0.35396142]), array([-0.10045632,  0.40244317,  0.35382282]), array([-0.10036979,  0.40240873,  0.35400136]), array([-0.10044128,  0.40245207,  0.3538473 ]), array([-0.11658262,  0.39505098,  0.40283863]), array([0.26663505, 0.18154523, 0.57397679]), array([0.30637081, 0.23244159, 0.40306903]), array([0.42885067, 0.06042871, 0.36349325]), array([0.44038827, 0.02147846, 0.35430922]), array([0.44038182, 0.02148146, 0.35434829]), array([0.44037791, 0.02149888, 0.35433262]), array([0.44038895, 0.0

,sample_nr,time,target_q_0,target_q_1,target_q_2,target_q_3,target_q_4,target_q_5,target_qd_0,target_qd_1,...,output_bit_register_71,output_bit_register_72,Normal operation,Damaged screw,Extra assembly component,Missing screw,Screw Loosening,x,y,z
0,278,0.00,0.086743,-1.085944,1.304110,-0.174707,-0.037001,-1.605179,0.000000,0.000000,...,False,False,False,False,False,False,True,0.306314,0.232461,0.403098
1,278,2.03,0.086604,-1.085948,1.304136,-0.174732,-0.037080,-1.605176,-0.007701,-0.000227,...,False,False,False,False,False,False,True,0.306334,0.232449,0.403087
2,278,4.04,-1.437947,-1.130811,1.591008,-0.447633,-0.906855,-1.576459,-0.615464,-0.018111,...,False,False,False,False,False,False,True,0.242503,-0.266050,0.359514
3,278,6.05,-1.627345,-1.136384,1.626647,-0.481536,-1.014909,-1.572891,0.000000,0.000000,...,False,False,False,False,False,False,True,0.188257,-0.302518,0.354346
4,278,8.05,-1.627345,-1.136384,1.626647,-0.481536,-1.014909,-1.572891,0.000000,0.000000,...,False,False,False,False,False,False,True,0.188227,-0.302545,0.354342

In [14]:
df = pd.read_feather('../data/aursad/aursad.feather')
df.head()

,sample_nr,time,target_q_0,target_q_1,target_q_2,target_q_3,target_q_4,target_q_5,target_qd_0,target_qd_1,...,output_bit_register_71,output_bit_register_72,Normal operation,Damaged screw,Extra assembly component,Missing screw,Screw Loosening,x,y,z
0,278,0.00,0.086743,-1.085944,1.304110,-0.174707,-0.037001,-1.605179,0.000000,0.000000,...,False,False,False,False,False,False,True,0.0,0.0,0.0
1,278,2.03,0.086604,-1.085948,1.304136,-0.174732,-0.037080,-1.605176,-0.007701,-0.000227,...,False,False,False,False,False,False,True,0.0,0.0,0.0
2,278,4.04,-1.437947,-1.130811,1.591008,-0.447633,-0.906855,-1.576459,-0.615464,-0.018111,...,False,False,False,False,False,False,True,0.0,0.0,0.0
3,278,6.05,-1.627345,-1.136384,1.626647,-0.481536,-1.014909,-1.572891,0.000000,0.000000,...,False,False,False,False,False,False,True,0.0,0.0,0.0
4,278,8.05,-1.627345,-1.136384,1.626647,-0.481536,-1.014909,-1.572891,0.000000,0.000000,...,False,False,False,False,False,False,True,0.0,0.0,0.0

In [ ]:
path = '../data/cobotops/cobotops_added_q.feather'

df = pd.read_feather(path)
df.head()

df_angles = df[['q0', 'q1', 'q2', 'q3', 'q4', 'q5']]
animation_sequence = df_angles.values.tolist()

# print(animation_sequence)

pos_lst = []
for frame in animation_sequence:
    pos = UR3_arm.forward_kinematics(frame)
    
    pos_lst.append(pos[:3,3])

print(pos_lst)
df = pd.concat([df.reset_index(drop=True), pd.DataFrame(pos_lst, columns=['x', 'y', 'z']).reset_index(drop=True)], axis=1)
# df.to_feather(path)
df.head()

[array([0.32963989, 0.24236093, 0.35086523]), array([0.33676052, 0.18491823, 0.39752584]), array([0.33350844, 0.21977864, 0.34107184]), array([0.39688262, 0.14071498, 0.38660098]), array([0.3800498 , 0.07087592, 0.35210583]), array([0.18962081, 0.33114237, 0.36806867]), array([0.18135207, 0.33814782, 0.35691267]), array([0.16124662, 0.35876852, 0.35252369]), array([0.1698118 , 0.38397385, 0.34859813]), array([0.19373197, 0.29740517, 0.34538646]), array([0.32587112, 0.15730155, 0.52088334]), array([0.26291189, 0.32277918, 0.3870353 ]), array([0.27049759, 0.25727283, 0.42984094]), array([0.18106814, 0.32144004, 0.36946181]), array([0.18332689, 0.26347622, 0.34631375]), array([0.3159928 , 0.24480674, 0.36467129]), array([0.33226621, 0.19892447, 0.35757867]), array([0.30158504, 0.28122189, 0.34370546]), array([0.34498609, 0.21098621, 0.35283224]), array([0.28540045, 0.32989186, 0.36763276]), array([0.23478481, 0.280828  , 0.35977345]), array([0.19725667, 0.30747608, 0.35506351]), array([0.19784896, 0.31716521, 0.35595186]), array([0.1985697 , 0.31439751, 0.35611681]), array([0.20099915, 0.31097528, 0.35713981]), array([0.20561497, 0.30588839, 0.35671307]), array([0.20770372, 0.30540215, 0.35693989]), array([0.20646692, 0.30325196, 0.35767406]), array([0.20611358, 0.30265279, 0.35798708]), array([0.20287663, 0.30526626, 0.35998065]), array([0.18815449, 0.29505693, 0.35392854]), array([0.18491903, 0.28602381, 0.35001262]), array([0.18752576, 0.30415342, 0.35954892]), array([0.19103824, 0.30617589, 0.35887319]), array([0.21563276, 0.33916489, 0.35721641]), array([0.30183375, 0.2438948 , 0.35789907]), array([0.25046444, 0.30548191, 0.35817431]), array([0.27712858, 0.27004972, 0.37171217]), array([0.22418954, 0.32191542, 0.36041917]), array([0.2055777 , 0.32556107, 0.35780998]), array([0.24515235, 0.29324947, 0.34608241]), array([0.29013658, 0.25665486, 0.38986636]), array([0.25226619, 0.2625518 , 0.41279659]), array([0.31513689, 0.25858992, 0.35999559]), array([0.18576439, 0.25760817, 0.33771276]), array([0.17688593, 0.28238554, 0.34793088]), array([0.21058518, 0.27898206, 0.3529057 ]), array([0.20266821, 0.30754255, 0.35746304]), array([0.20377407, 0.31803671, 0.35884678]), array([0.21849504, 0.31576733, 0.36965011]), array([0.24396617, 0.33711017, 0.36716035]), array([0.17518791, 0.31185688, 0.35305466]), array([0.33181076, 0.10667439, 0.35920716]), array([0.24536565, 0.3286812 , 0.36834419]), array([0.23225631, 0.30413531, 0.37080567]), array([0.39487812, 0.08217665, 0.34125798]), array([0.32200063, 0.25687839, 0.36713539]), array([0.33355694, 0.21376407, 0.35842616]), array([0.2664537 , 0.26568665, 0.35832788]), array([0.24702362, 0.27375573, 0.35922093]), array([0.25859933, 0.2650202 , 0.35970024]), array([0.25014537, 0.26448881, 0.35945571]), array([0.25166963, 0.26933783, 0.35823189]), array([0.24906232, 0.27035278, 0.35743688]), array([0.24313243, 0.27178397, 0.35577081]), array([0.23502269, 0.27729087, 0.35490445]), array([0.23952118, 0.26594375, 0.35614613]), array([0.24401649, 0.26280334, 0.35649533]), array([0.22966703, 0.26427314, 0.35550481]), array([0.24708582, 0.26357824, 0.35617218]), array([0.23399822, 0.26546162, 0.35681877]), array([0.23932805, 0.26950826, 0.3561002 ]), array([0.24682659, 0.25785201, 0.35777605]), array([0.18400968, 0.36995423, 0.3548159 ]), array([0.38029503, 0.1159612 , 0.46082444]), array([0.24715669, 0.30928376, 0.38834951]), array([0.273307  , 0.27718073, 0.36091524]), array([0.32499084, 0.26024979, 0.37845695]), array([0.22218022, 0.32775215, 0.36176695]), array([0.21837294, 0.31165226, 0.35877577]), array([0.24018962, 0.296739  , 0.359398  ]), array([0.23401962, 0.30075857, 0.36179936]), array([0.22477668, 0.30318929, 0.35923203]), array([0.21738615, 0.30746399, 0.35858362]), array([0.241761  , 0.32114196, 0.36403052]), array([0.21405702, 0.3241783 , 0.35958317]), array([0.2834263 , 0.21425232, 0.39710681]), array([0.33702557, 0.2094606 , 0.36541305]), array([0.12374573, 0.25136767, 0.52810851]), array([0.36471766, 0.26104731, 0.36770132]), array([0.21264301, 0.27559307, 0.33822695]), array([0.16927248, 0.34034115, 0.35980174]), array([0.2159577 , 0.33889226, 0.35641104]), array([0.24739001, 0.31045359, 0.36173323]), array([0.21458895, 0.33187129, 0.36721956]), array([0.18637784, 0.35218727, 0.33989639]), array([0.38300835, 0.11729461, 0.35008961]), array([0.26916185, 0.2421115 , 0.48996576]), array([0.15517087, 0.23783997, 0.39860302]), array([0.19849307, 0.30617888, 0.37034635]), array([0.21412309, 0.20391708, 0.41280726]), array([0.31160087, 0.24940863, 0.3657905 ]), array([0.28689651, 0.27968307, 0.35685061]), array([0.24533538, 0.37758483, 0.34752281]), array([0.38122288, 0.13587595, 0.37324601]), array([0.37693883, 0.11720011, 0.37538677]), array([0.07530421, 0.23587711, 0.34691535]), array([0.31625401, 0.27020468, 0.3918172 ]), array([0.25995568, 0.30221051, 0.36250152]), array([0.20383875, 0.32787297, 0.36326685]), array([0.20037912, 0.32507808, 0.36195438]), array([0.24291685, 0.30781214, 0.34938557]), array([0.24615855, 0.33435405, 0.36407712]), array([0.30255259, 0.23316937, 0.43920471]), array([0.37115152, 0.10171054, 0.34527093]), array([0.00587297, 0.2486953 , 0.38579221]), array([0.19640972, 0.34174799, 0.34746437]), array([0.13714846, 0.37216348, 0.34635085]), array([0.20206628, 0.31051981, 0.35768042]), array([0.18187728, 0.36508476, 0.35195117]), array([0.19289897, 0.29686664, 0.34766878]), array([0.30633897, 0.13994387, 0.5543828 ]), array([0.27280069, 0.30696411, 0.375494  ]), array([0.33532819, 0.17148817, 0.35297628]), array([0.16451945, 0.29790904, 0.35650963]), array([0.25325871, 0.2603529 , 0.35163668]), array([0.29776413, 0.20283587, 0.35709444]), array([0.36268561, 0.05264705, 0.34124112]), array([0.33268803, 0.23288105, 0.33864978]), array([0.35086073, 0.16769034, 0.39890915]), array([0.3737496 , 0.14177726, 0.35827716]), array([0.14995487, 0.37797974, 0.3557519 ]), array([0.28293861, 0.31673287, 0.37509428]), array([0.18959081, 0.34948928, 0.36365084]), array([0.18876764, 0.33037338, 0.36150516]), array([0.26213205, 0.19797541, 0.38999634]), array([0.38379256, 0.09071137, 0.34344181]), array([0.29229401, 0.34815477, 0.34788642]), array([0.40583458, 0.15799264, 0.35381749]), array([0.20538656, 0.23472634, 0.38196625]), array([0.16520482, 0.32255407, 0.35495018]), array([0.2820205 , 0.24778584, 0.36423411]), array([0.20207585, 0.30351159, 0.36154986]), array([0.17814023, 0.36705655, 0.35836575]), array([0.1930776 , 0.35565064, 0.3428662 ]), array([0.3756711 , 0.14332931, 0.34861401]), array([0.24612968, 0.21620144, 0.44099375]), array([0.16645428, 0.23101422, 0.41691507]), array([0.21595711, 0.28738553, 0.3759852 ]), array([0.25079401, 0.20539938, 0.501012  ]), array([0.37040532, 0.18559577, 0.36817322]), array([0.32710556, 0.22883302, 0.35408091]), array([0.22666935, 0.33593484, 0.34538355]), array([0.34402446, 0.15708749, 0.48974519]), array([0.25896372, 0.28750002, 0.39468438]), array([0.25489228, 0.31060768, 0.35871494]), array([0.3102787 , 0.27339288, 0.38925981]), array([0.23971796, 0.31425049, 0.3729897 ]), array([0.2073688 , 0.32526487, 0.36197954]), array([0.21277431, 0.31877423, 0.36222747]), array([0.2134426 , 0.32000521, 0.36200136]), array([0.20054163, 0.32215579, 0.36206632]), array([0.2031254 , 0.31750529, 0.36235253]), array([0.20479271, 0.31928611, 0.36259643]), array([0.21005794, 0.31608196, 0.36317935]), array([0.20762772, 0.31935433, 0.36178139]), array([0.21531802, 0.31188977, 0.36072967]), array([0.22095028, 0.31081581, 0.36191677]), array([0.21752105, 0.31316287, 0.36247585]), array([0.21687779, 0.31189141, 0.36096493]), array([0.21344798, 0.31164617, 0.3611022 ]), array([0.18479447, 0.21530918, 0.36073871]), array([0.26067416, 0.29557781, 0.36140072]), array([0.26316238, 0.27377253, 0.36963674]), array([0.27384552, 0.23094705, 0.36524315]), array([0.2832273 , 0.25326113, 0.40110404]), array([0.21314858, 0.29424413, 0.36231883]), array([0.19755992, 0.28954243, 0.34918236]), array([0.23901279, 0.29227801, 0.35786861]), array([0.22861005, 0.32055361, 0.37049472]), array([0.17344689, 0.35235428, 0.33779159]), array([0.19379672, 0.28661894, 0.34358294]), array([0.21527021, 0.31620588, 0.38145343]), array([0.28841049, 0.26602061, 0.37640144]), array([0.21029275, 0.30865562, 0.36480017]), array([0.35432286, 0.15487752, 0.34749655]), array([0.24117911, 0.28328456, 0.35806747]), array([0.32750371, 0.1869278 , 0.34983108]), array([0.222474 , 0.3422973, 0.3394087]), array([0.39534213, 0.06439752, 0.44860108]), array([0.25854375, 0.29162839, 0.39105229]), array([0.26632175, 0.28286523, 0.35985942]), array([0.33458988, 0.22939097, 0.38332475]), array([0.21522904, 0.3335371 , 0.36369724]), array([0.22272121, 0.3176063 , 0.35814272]), array([0.22900468, 0.30218514, 0.36051236]), array([0.21671442, 0.31025385, 0.36074731]), array([0.22020123, 0.30629457, 0.36047971]), array([0.21565802, 0.30702301, 0.3612567 ]), array([0.22204154, 0.30487395, 0.36147349]), array([0.27246641, 0.34886136, 0.35397207]), array([0.2128242 , 0.26896845, 0.34986445]), array([0.27461798, 0.28914051, 0.35709463]), array([0.27418997, 0.30476651, 0.37729269]), array([0.28269236, 0.17942078, 0.5664934 ]), array([0.36097205, 0.15091386, 0.36507627]), array([0.36056901, 0.13602736, 0.36141623]), array([0.20913304, 0.32798756, 0.36501682]), array([0.2788338 , 0.27562344, 0.36060131]), array([0.23288051, 0.29869038, 0.36374531]), array([0.16055696, 0.3776059 , 0.35053199]), array([0.1807106 , 0.31341539, 0.34774689]), array([0.31005361, 0.13991615, 0.55565815]), array([0.28591604, 0.30141809, 0.36378886]), array([0.18358004, 0.30739683, 0.36412241]), array([0.22176443, 0.29284554, 0.35074723]), array([0.29700352, 0.26161026, 0.36303023]), array([0.26659799, 0.2594506 , 0.35089096]), array([0.3569178 , 0.15112867, 0.36808893]), array([0.30363748, 0.22024142, 0.34482703]), array([0.35735485, 0.16951675, 0.39231888]), array([0.36917364, 0.11398175, 0.37558691]), array([0.32771138, 0.26105203, 0.36837482]), array([0.26931345, 0.30888992, 0.37275776]), array([0.22925748, 0.32253261, 0.36185069]), array([0.20506165, 0.33104998, 0.35925564]), array([0.23670545, 0.31797517, 0.34871747]), array([0.34835526, 0.18542875, 0.38924569]), array([0.28383652, 0.21307606, 0.40895904]), array([0.22383311, 0.36738788, 0.35071312]), array([0.22915656, 0.22276515, 0.33903325]), array([0.22273803, 0.31935863, 0.35200493]), array([0.24837744, 0.28167494, 0.35774149]), array([0.23293011, 0.28926345, 0.35567174]), array([0.17031461, 0.37462429, 0.34766324]), array([0.19074245, 0.29240435, 0.33930523]), array([0.34743687, 0.12163343, 0.50340067]), array([0.28517754, 0.30580558, 0.38922559]), array([0.32098192, 0.21802929, 0.4682931 ]), array([0.17593477, 0.30576391, 0.37217288]), array([0.18722031, 0.24845976, 0.35988757]), array([0.31231216, 0.22524897, 0.36099398]), array([0.27916765, 0.24949234, 0.35490722]), array([0.37723376, 0.15253391, 0.35406102]), array([0.35019589, 0.16926132, 0.43772576]), array([0.39089019, 0.09989214, 0.36137919]), array([0.21123623, 0.35157855, 0.34289945]), array([0.30289674, 0.2851339 , 0.36918279]), array([0.21870713, 0.33413011, 0.36557038]), array([0.20191844, 0.32987249, 0.35978804]), array([0.31411033, 0.25120817, 0.3520589 ]), array([0.35213826, 0.17961459, 0.37929922]), array([0.20545919, 0.23905499, 0.5599239 ]), array([0.31618491, 0.28632808, 0.37090546]), array([0.23987183, 0.23880091, 0.35298123]), array([0.28436012, 0.28035541, 0.3477586 ]), array([0.3386191 , 0.18543939, 0.35037123]), array([0.29280706, 0.23463605, 0.34945685]), array([0.17102476, 0.37999098, 0.35104545]), array([0.18571744, 0.30930128, 0.34469299]), array([0.35519424, 0.1466764 , 0.48522898]), array([0.25540595, 0.32314927, 0.35381962]), array([0.2879984 , 0.23994042, 0.41068602]), array([0.16326021, 0.30694642, 0.36161707]), array([0.23082372, 0.26274819, 0.39587453]), array([0.30960881, 0.24842516, 0.36619859]), array([0.27758522, 0.25202689, 0.35517292]), array([0.16583689, 0.38826485, 0.34944716]), array([0.37915811, 0.11925569, 0.42877224]), array([0.23255185, 0.33869223, 0.34999421]), array([0.15223179, 0.39272834, 0.35152142]), array([0.28858929, 0.30251383, 0.38466613]), array([0.21564849, 0.34138151, 0.36884594]), array([0.20832669, 0.33937688, 0.36131052]), array([0.27608708, 0.22156806, 0.40408861]), array([0.35133293, 0.18875672, 0.3757778 ]), array([0.21301314, 0.19760871, 0.47797003]), array([0.37251763, 0.27524924, 0.36591599]), array([0.26985331, 0.26334108, 0.34133564]), array([0.18485688, 0.34760401, 0.35618954]), array([0.24085037, 0.3004827 , 0.36144056]), array([0.23072894, 0.31809634, 0.35626883]), array([0.17350215, 0.36287217, 0.35705093]), array([0.17930294, 0.35121899, 0.33434054]), array([0.38452698, 0.11212617, 0.33852773]), array([0.30660378, 0.19437311, 0.5067913 ]), array([0.26691364, 0.2158436 , 0.51158901]), array([0.20905616, 0.2956875 , 0.37187744]), array([0.19018016, 0.20903399, 0.58052428]), array([0.30624049, 0.26667982, 0.36233314]), array([0.28054853, 0.27860725, 0.35486768]), array([0.34537613, 0.21124863, 0.34270878]), array([0.31148699, 0.22425999, 0.3420028 ]), array([0.37416925, 0.11699666, 0.36694186]), array([0.36396928, 0.18514584, 0.37655609]), array([0.32622769, 0.25838465, 0.3841749 ]), array([0.25860728, 0.3231024 , 0.35664545]), array([0.23790921, 0.33140856, 0.35394002]), array([0.17017165, 0.23321145, 0.35002341]), array([0.26587349, 0.30311359, 0.35223359]), array([0.29560774, 0.31054348, 0.37535863]), array([0.34940471, 0.23274401, 0.35052786]), array([0.14515828, 0.32440785, 0.3327048 ]), array([0.29219005, 0.11713101, 0.37549018]), array([0.33663668, 0.22310448, 0.38647131]), array([0.36047653, 0.2337719 , 0.36123724]), array([0.28138475, 0.29707953, 0.36613548]), array([0.16301805, 0.38374385, 0.35102379]), array([0.18395757, 0.28984486, 0.34148853]), array([0.21467955, 0.18488142, 0.48917668]), array([0.28914095, 0.30050355, 0.36355202]), array([0.35294653, 0.15999213, 0.36483724]), array([0.21018716, 0.28122727, 0.35175431]), array([0.27114806, 0.2860033 , 0.35520018]), array([0.3603751 , 0.17987506, 0.35737981]), array([0.36861691, 0.11934755, 0.36174675]), array([0.26841031, 0.26911772, 0.34651901]), array([0.3677159 , 0.15155508, 0.34878924]), array([0.36941049, 0.18562817, 0.38737443]), array([0.25056099, 0.3425667 , 0.36370727]), array([0.28780993, 0.29074243, 0.37701839]), array([0.24264637, 0.32742598, 0.36445891]), array([0.21811314, 0.33023735, 0.3618655 ]), array([0.23578467, 0.32124657, 0.3521503 ]), array([0.36878876, 0.15024076, 0.37847278]), array([0.2881689 , 0.17471058, 0.58569412]), array([0.27884828, 0.3359638 , 0.35771147]), array([0.38615645, 0.21156948, 0.363439  ]), array([0.25118827, 0.3107728 , 0.36413146]), array([0.22905013, 0.28548815, 0.35788288]), array([0.22525057, 0.30058464, 0.35485386]), array([0.17019152, 0.38757214, 0.34364137]), array([0.18208343, 0.30234984, 0.33938316]), array([0.34655603, 0.14170462, 0.46463859]), array([0.28638612, 0.3119955 , 0.39395966]), array([0.28737027, 0.25780071, 0.43391599]), array([0.17587972, 0.32436553, 0.36776255]), array([0.21686421, 0.25485115, 0.37164573]), array([0.33538264, 0.23217001, 0.36695789]), array([0.27966694, 0.27100912, 0.35517474]), array([0.37611364, 0.17076664, 0.35285127]), array([0.38124325, 0.10837422, 0.49957138]), array([0.39096092, 0.09636012, 0.36255154]), array([0.20644209, 0.36571963, 0.33995449]), array([0.30986548, 0.29466034, 0.37556248]), array([0.21050373, 0.3475618 , 0.36204449]), array([0.19814294, 0.33926633, 0.35920881]), array([0.28159183, 0.24249167, 0.33794448]), array([0.37022283, 0.14073931, 0.38055078]), array([0.3132848 , 0.16029377, 0.54225931]), array([0.31619518, 0.28917548, 0.37636312]), array([0.13567582, 0.28626416, 0.33487793]), array([0.31272198, 0.2867956 , 0.34481909]), array([0.36105398, 0.17307346, 0.35755751]), array([0.28716385, 0.24435843, 0.3579862 ]), array([0.17168986, 0.38511014, 0.35408892]), array([0.17904489, 0.30295568, 0.34076764]), array([0.33016315, 0.20166671, 0.46938195]), array([0.26252157, 0.29295875, 0.40664865]), array([0.30478458, 0.20912605, 0.35456014]), array([0.15692243, 0.33245131, 0.36422942]), array([0.18266701, 0.20398558, 0.53992069]), array([0.33811789, 0.24261936, 0.35975121]), array([0.31504318, 0.25105757, 0.35955669]), array([0.31126634, 0.28414586, 0.35272278]), array([0.30243134, 0.23170348, 0.35999024]), array([0.38132582, 0.11853562, 0.38748958]), array([0.14247787, 0.40408071, 0.34312425]), array([0.33171099, 0.24753481, 0.38897922]), array([0.20335908, 0.34913332, 0.36715083]), array([0.21210785, 0.32971287, 0.36152494]), array([0.209505  , 0.20804261, 0.36671354]), array([0.38278524, 0.13892249, 0.35780245]), array([0.28107985, 0.33607873, 0.34024981]), array([0.33516227, 0.15415678, 0.36881913]), array([0.28004067, 0.22430482, 0.37657442]), array([0.22476004, 0.28186738, 0.35304621]), array([0.17920649, 0.28711787, 0.35461047]), array([0.2303637 , 0.28285754, 0.35784624]), array([0.21839604, 0.30579387, 0.35956501]), array([0.20590541, 0.37311405, 0.34196033]), array([0.19299634, 0.29635805, 0.34876724]), array([0.26340349, 0.21630681, 0.36488552]), array([0.25392291, 0.28703987, 0.37614232]), array([0.29459336, 0.23660662, 0.36836087]), array([0.29647979, 0.28950742, 0.35836797]), array([0.2737023 , 0.25587379, 0.36387507]), array([0.2653985 , 0.25742355, 0.35344602]), array([0.19850422, 0.36245122, 0.3527932 ]), array([0.386283  , 0.12261935, 0.43901264]), array([0.18214543, 0.35965608, 0.35935531]), array([0.20890026, 0.32802843, 0.35418553]), array([0.22128539, 0.32233241, 0.35799222]), array([0.27704638, 0.29096621, 0.36783715]), array([0.30117376, 0.26372659, 0.36628724]), array([0.32498095, 0.26142339, 0.38205464]), array([0.25180827, 0.30878088, 0.36801831]), array([0.22181872, 0.3312061 , 0.35755542]), array([0.212617  , 0.32559336, 0.35759371]), array([0.25604043, 0.2958139 , 0.3481985 ]), array([ 0.34918549, -0.01516406,  0.36202149]), array([0.29453305, 0.22427529, 0.3902373 ]), array([0.3342362 , 0.25667234, 0.38843327]), array([0.1856427 , 0.26791521, 0.34227727]), array([0.13561538, 0.2763396 , 0.35107712]), array([0.16629937, 0.28592965, 0.35425475]), array([0.17532337, 0.29643342, 0.36199533]), array([0.2058797 , 0.374385  , 0.34656935]), array([0.19561629, 0.2967142 , 0.34630285]), array([0.32609582, 0.16969874, 0.4861481 ]), array([0.28648073, 0.30315587, 0.39198611]), array([0.2683259 , 0.25744115, 0.43409843]), array([0.16827622, 0.31978541, 0.36456176]), array([0.2017275 , 0.25618514, 0.36972148]), array([0.35321573, 0.19282455, 0.37053335]), array([0.27587458, 0.28456585, 0.3560989 ]), array([0.24906545, 0.23980799, 0.34010347]), array([0.36374689, 0.20139261, 0.36654102]), array([0.27792675, 0.27676488, 0.36323336]), array([0.26047251, 0.30788752, 0.36111975]), array([0.28277528, 0.28884517, 0.37369988]), array([0.21592136, 0.33941068, 0.36053431]), array([0.21007959, 0.3311272 , 0.3594481 ]), array([0.23791159, 0.31765133, 0.35405307]), array([0.33274413, 0.20044945, 0.39544864]), array([0.35696166, 0.17694188, 0.43164655]), array([0.26978292, 0.31509594, 0.38439355]), array([0.33933409, 0.09445206, 0.3041619 ]), array([0.37708328, 0.18771887, 0.37343364]), array([0.20065948, 0.33803824, 0.36356839]), array([0.21615358, 0.33109381, 0.35665944]), array([0.18257866, 0.36232897, 0.35325757]), array([0.18523123, 0.31106004, 0.34184293]), array([0.35452102, 0.09573378, 0.4977672 ]), array([0.30034796, 0.28220366, 0.38338812]), array([0.28660666, 0.21583125, 0.52126102]), array([0.17837931, 0.30585095, 0.36747271]), array([0.18487202, 0.30378674, 0.34691275]), array([0.34968512, 0.14646006, 0.35508785]), array([0.28119862, 0.20693663, 0.33939823]), array([0.30034228, 0.29773587, 0.33365651]), array([0.36992949, 0.1541375 , 0.34043964]), array([0.38627176, 0.10489251, 0.36602147]), array([0.18633219, 0.36043813, 0.34853407]), array([0.33039012, 

,Current0,Current1,Current2,Current3,Current4,Current5,Robot_ProtectiveStop,Speed0,Speed1,Speed2,...,time,q0,q1,q2,q3,q4,q5,x,y,z
0,0.109628,-2.024669,-1.531442,-0.998570,-0.062540,-0.152622,0.0,2.955651e-01,-0.000490,0.001310,...,0,0.109037,-0.891345,1.237855,-0.341876,1.302277,-1.567965,0.329640,0.242361,0.350865
1,0.595605,-2.278456,-0.866556,-0.206097,-1.062762,-0.260764,0.0,-7.391485e-30,-0.000304,0.002185,...,1,-0.060834,-1.082017,1.324816,-0.200118,0.220923,-1.601074,0.336761,0.184918,0.397526
2,-0.229474,-2.800408,-2.304336,-0.351499,-0.668869,0.039071,0.0,1.369386e-01,0.007795,-2.535874,...,2,0.043552,-0.920171,1.338099,-0.414386,1.549299,-1.566776,0.333508,0.219779,0.341072
3,0.065053,-3.687768,-1.217652,-1.209115,-0.819755,0.153903,0.0,-9.030032e-02,-0.004911,-0.009096,...,3,-0.167872,-0.877175,1.039600,-0.143168,1.301707,-1.576724,0.396883,0.140715,0.386601
4,0.884140,-2.938830,-1.794076,-2.356471,-0.966427,0.178998,0.0,1.268088e-01,0.005567,0.001138,...,4,-0.374688,-1.001313,1.420650,-0.399870,1.583917,-1.573527,0.380050,0.070876,0.352106

In [12]:
df.head()

,Current0,Current1,Current2,Current3,Current4,Current5,Robot_ProtectiveStop,Speed0,Speed1,Speed2,...,time,q0,q1,q2,q3,q4,q5,x,y,z
0,0.109628,-2.024669,-1.531442,-0.998570,-0.062540,-0.152622,0.0,2.955651e-01,-0.000490,0.001310,...,0,0.109037,-0.891345,1.237855,-0.341876,1.302277,-1.567965,0.0,0.0,0.0
1,0.595605,-2.278456,-0.866556,-0.206097,-1.062762,-0.260764,0.0,-7.391485e-30,-0.000304,0.002185,...,1,-0.060834,-1.082017,1.324816,-0.200118,0.220923,-1.601074,0.0,0.0,0.0
2,-0.229474,-2.800408,-2.304336,-0.351499,-0.668869,0.039071,0.0,1.369386e-01,0.007795,-2.535874,...,2,0.043552,-0.920171,1.338099,-0.414386,1.549299,-1.566776,0.0,0.0,0.0
3,0.065053,-3.687768,-1.217652,-1.209115,-0.819755,0.153903,0.0,-9.030032e-02,-0.004911,-0.009096,...,3,-0.167872,-0.877175,1.039600,-0.143168,1.301707,-1.576724,0.0,0.0,0.0
4,0.884140,-2.938830,-1.794076,-2.356471,-0.966427,0.178998,0.0,1.268088e-01,0.005567,0.001138,...,4,-0.374688,-1.001313,1.420650,-0.399870,1.583917,-1.573527,0.0,0.0,0.0